### PR TITLE
Add phantom

### PR DESCRIPTION
**Pull request by wzel**
Add \phantom{} support.

### CODE REVIEW

**Review by gtalckmin — CHANGES_REQUESTED** [review]
Hi, does this add the \phantom command ?
I tried from the wzel github package, however the \\phantom{whatever} is mapped a string not as a latex command. 
It would be great to have this functionality as this would allow parsing parts of a math expression under phantom (other parts, not) and, using several annotations, have a colourized annotation on ggplot2.

**Comment by wzel** [comment]
Hi,

I just checked, and it works for me in annotations:

```r
library(ggplot2)
library(latex2exp)

ggplot(data.frame(x = 1:2, y = 1:2),
       aes(x = x, y = y)) +
   geom_point() +
   annotate("text",
            x = 1.5, y = 1.5,
            label = TeX("a\\phantom{b}c"),
            parse = TRUE)
```

**Comment by gtalckmin** [comment]
This is what I have as output:
phantom
with this warning message:
```
Warning message:
In is.na(x) : is.na() applied to non-(list or vector) of type 'expression'
```
I installed the package from your repository using 
devtools::install_github("wzel/latex2exp")

these are the versions of the libraries installed.
[1] latex2exp_0.4.0 ggplot2_3.3.2  

Runing  R version 4.02, Rstudio/Windows 10

**Solution**
devtools::install_github(repo = "wzel/latex2exp", ref = "add-phantom")

PS: sorry was my mistake! Thanks for that , mate

**Comment by wzel** [comment]
Glad that you find this useful.

**Review by stefano-meschiari — APPROVED** [review]
Looks good! Sorry for the delay in checking out and merging this PR — I'm just now catching up and implementing some of the improvements I had in the backlog.

**Pull request merged**
